create database if not exists FINANCEIRO;
USE FINANCEIRO;

CREATE TABLE IF NOT EXISTS USUARIO_CADASTRO(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_USUARIO VARCHAR(50) UNIQUE,
CADASTRO_NOME_COMPLETO VARCHAR (100) NOT NULL,
CADASTRO_NASC DATE NOT NULL,
PAIS VARCHAR(20),
ESTADO CHAR(2),
--  DEPOIS COLOCAR UMA RESTRICAO USANDO O CHK Para o email e senha

CADASTRO_EMAIL VARCHAR(20) NOT NULL UNIQUE,
DATA_CRIACAO_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
ATIVO BOOL NOT NULL DEFAULT TRUE);

CREATE TABLE  IF NOT EXISTS AUTENTICACAO(
ID_AUTENTICACAO INT   PRIMARY KEY AUTO_INCREMENT,
AUTENTICACAO_USUARIO INT NOT NULL,
SENHA_HASH VARCHAR(255) NOT NULL,-- O hash da senha (nunca a senha pura)
ULTIMO_LOGIN DATETIME DEFAULT CURRENT_TIMESTAMP,
-- Definição da Chave Estrangeira: Garante que só existe autenticação para um usuário existente

CONSTRAINT FK_AUTEN_CADASTRO FOREIGN KEY(AUTENTICACAO_USUARIO)
REFERENCES USUARIO_CADASTRO(ID_USUARIO)
ON DELETE  CASCADE-- Se o usuário for deletado, deleta a autenticação
ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS RECUPERA_SENHA(
ID_TOKEN INT AUTO_INCREMENT PRIMARY KEY,
RECUPERA_SENHA_USUARIO INT NOT NULL,
TOKEN VARCHAR (255)NOT NULL UNIQUE,
DATA_SOLICITACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
DATA_EXPEDICAO DATETIME NOT NULL,
ULTILIZADO BOOL NOT NULL DEFAULT FALSE,

CONSTRAINT FK_SENHA_USUARIO FOREIGN KEY(RECUPERA_SENHA_USUARIO)
REFERENCES USUARIO_CADASTRO(ID_USUARIO)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS DADOS(
ID_DADOS INT AUTO_INCREMENT PRIMARY KEY,
FK_DADOS_USUARIO INT NOT NULL,
CONSTRAINT FK_DADOS_USUARIO FOREIGN KEY(FK_DADOS_USUARIO)
REFERENCES USUARIO_CADASTRO(ID_USUARIO)
-- AINDA DECIDIR SE IRA RESTRINGIR OU NÃO 
);
CREATE TABLE IF NOT EXISTS PAGAMENTO_ENTRADA(
ID_ENTRADA INT PRIMARY KEY,
FK_ID_USUARIO INT  NOT NULL,
DIA_HORA_ACESSO DATETIME DEFAULT CURRENT_TIMESTAMP,
DATA_PERVISTA_ENTRADA DATE ,
DATA_REAL_ENTRADA DATE NOT NULL,
EMPRESTIMO_ENTRADA TINYINT NOT NULL,
ENTRADA_DEBITO DECIMAL (10,2),
ENTRADA_PIX DECIMAL(10,2),
ENTRADA_DINHEIRO DECIMAL(10,2),
DESCRICAO_ENTRADA TEXT NULL,
-- AS FKS DA TABELA ENTRADA
 FOREIGN KEY(FK_ID_USUARIO) REFERENCES USUARIO_CADASTRO(ID_USUARIO)
ON DELETE RESTRICT #RESTRINGINDO 
ON UPDATE CASCADE );

CREATE TABLE IF NOT EXISTS DINHEIRO(
ID_DINHEIRO INT AUTO_INCREMENT PRIMARY KEY,
FK_DINHEIRO_ENTRADA INT NOT NULL,
VALOR_COMPRA_DINHEIRO DECIMAL(10,2),
DATA_PAGAMENTO_DINHEIRO DATE NOT NULL,
DESCRICAO_PAGAMENTO_DINHEIRO TEXT,
CONSTRAINT FK_DEBITO_ENTRADA FOREIGN KEY(FK_DINHEIRO_ENTRADA)
REFERENCES PAGAMENTO_ENTRADA(ID_ENTRADA)
);

CREATE TABLE IF NOT EXISTS DEBITO(
ID_DEBITO INT AUTO_INCREMENT PRIMARY KEY,
FK_ENTRADA INT NOT NULL,
NOME_CARTAO_DEBITO VARCHAR(20) NOT NULL,
NUMERO_CONTA_DEBITO INT NOT NULL UNIQUE,
VALOR_CARTAO_DEBITO DECIMAL(10,2)NOT NULL,
VALOR_DEBITO_PIX DECIMAL(10,2)NOT NULL,
VALOR_BOLETO DECIMAL(10,2)NOT NULL,
DATA_PAGAMENTO DATE NOT NULL,
DESCRICAO_PAGO_DEBITO TEXT,
CONSTRAINT FK_ENTRADA FOREIGN KEY(FK_ENTRADA)
REFERENCES PAGAMENTO_ENTRADA(ID_ENTRADA)
);

CREATE TABLE IF NOT EXISTS CARTAO_CREDITO(
ID_CREDITO INT AUTO_INCREMENT PRIMARY KEY ,
FK_DEBITO INT NOT NULL,
NOME_CARTAO_CREDITO VARCHAR(20) NOT NULL,
NUMERO_CARTAO_CREDITO VARCHAR(20) NOT NULL UNIQUE,
VALOR_COMPRA_CREDITO DECIMAL(10,2) NOT NULL,
DATA_PAGAMENTO_CREDITO DATE NOT NULL,	
DESCRICAO_PAGAMENTO_CREDITO TEXT,
CONSTRAINT CREDITO_DEBITO FOREIGN KEY(FK_DEBITO)
REFERENCES DEBITO (ID_DEBITO));


CREATE TABLE IF NOT EXISTS  FORMA_PAGAMENTO(
ID_FORMA_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
TIPO_PAGAMENTO VARCHAR(20),
FK_DEBITO INT NOT NULL,
FK_DINHEIRO INT NOT NULL, 
CONSTRAINT FK_DINHEIRO FOREIGN KEY (FK_DINHEIRO)
REFERENCES DINHEIRO(ID_DINHEIRO),
CONSTRAINT FK_DEBITO FOREIGN KEY(FK_DEBITO)
REFERENCES DEBITO(ID_DEBITO),
FK_CARTAO_CREDITO INT NOT NULL,
CONSTRAINT FK_CARTAO_CREDITO FOREIGN KEY (FK_CARTAO_CREDITO)
REFERENCES CARTAO_CREDITO(ID_CREDITO)
);
CREATE TABLE IF NOT EXISTS PARCELAS(
ID_PARCELAS INT AUTO_INCREMENT PRIMARY KEY,
MES_REFERENCIA_PARCELA DATE NOT NULL,
VALOR_PARCELA DECIMAL(10,2) NOT NULL,
NUMERO_PARCELA INT NOT NULL,
TOTAL_PARCELA INT NOT NULL,
STATUS_PARCELAS  VARCHAR(20),
DESCRICAO_PARCELA TEXT
);

/*CREATE TABLE IF NOT EXISTS PARCELAS_CREDITO(
);--TABELA ASSOCIATIVA NO FINAL TODAS*/


-- CREATE TABLE IF NOT EXISTS METODO_PAGAMENTO


-- DEPOIS DA ETAPA DE CRIAR O BANCO DE DADOS E CRIA AS INDEX 




